# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 441, 511))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 461))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.img_btn.setObjectName("img_btn")
        self.horizontalLayout_5.addWidget(self.img_btn)
        self.img_path = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.img_path.setText("")
        self.img_path.setObjectName("img_path")
        self.horizontalLayout_5.addWidget(self.img_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.msg_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.msg_btn.setObjectName("msg_btn")
        self.horizontalLayout_6.addWidget(self.msg_btn)
        self.msg_path = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.msg_path.setText("")
        self.msg_path.setObjectName("msg_path")
        self.horizontalLayout_6.addWidget(self.msg_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.msg_plain = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.msg_plain.setObjectName("msg_plain")
        self.verticalLayout_2.addWidget(self.msg_plain)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_N_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_N_2.setObjectName("label_N_2")
        self.horizontalLayout_7.addWidget(self.label_N_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.N = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.N.setObjectName("N")
        self.horizontalLayout_7.addWidget(self.N)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_K_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_K_2.setObjectName("label_K_2")
        self.horizontalLayout_8.addWidget(self.label_K_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.K = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.K.setObjectName("K")
        self.horizontalLayout_8.addWidget(self.K)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.hide_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.hide_btn.setObjectName("hide_btn")
        self.verticalLayout_2.addWidget(self.hide_btn)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 412, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.simg_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.simg_btn.setObjectName("simg_btn")
        self.horizontalLayout_9.addWidget(self.simg_btn)
        self.simg_path = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.simg_path.setText("")
        self.simg_path.setObjectName("simg_path")
        self.horizontalLayout_9.addWidget(self.simg_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.key_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.key_btn.setObjectName("key_btn")
        self.horizontalLayout_10.addWidget(self.key_btn)
        self.key_path = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.key_path.setText("")
        self.key_path.setObjectName("key_path")
        self.horizontalLayout_10.addWidget(self.key_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.reveal_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.reveal_btn.setObjectName("reveal_btn")
        self.verticalLayout_3.addWidget(self.reveal_btn)
        self.tabWidget.addTab(self.tab_2, "")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(10, 530, 441, 101))
        self.status.setMinimumSize(QtCore.QSize(0, 50))
        self.status.setText("")
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Steg-D"))
        self.label_4.setText(_translate("MainWindow", "Выберите изображение для встраивания:"))
        self.img_btn.setText(_translate("MainWindow", "Изображение-контейнер"))
        self.label_5.setText(_translate("MainWindow", "Выберите файл, который хотите скрыть:"))
        self.msg_btn.setText(_translate("MainWindow", "Сообщение"))
        self.label_6.setText(_translate("MainWindow", "Или задайте сообщение здесь:"))
        self.label_N_2.setText(_translate("MainWindow", "Кол-во частей секрета N"))
        self.label_K_2.setText(_translate("MainWindow", "Пороговое значение K"))
        self.hide_btn.setText(_translate("MainWindow", "Встроить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Встроить информацию"))
        self.label_7.setText(_translate("MainWindow", "Выберите изображение для раскрытия:"))
        self.simg_btn.setText(_translate("MainWindow", "Изображение-контейнер"))
        self.label_8.setText(_translate("MainWindow", "Выберите файл, содержащий количество частей секрета:"))
        self.key_btn.setText(_translate("MainWindow", "Ключ"))
        self.reveal_btn.setText(_translate("MainWindow", "Раскрыть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Раскрыть информацию"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Открыть конфиг"))
        self.action_2.setText(_translate("MainWindow", "Сохранить конфиг"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
